"""Protocol describing the shared MenuScreen contract between core and mixins.

``MenuScreenCore`` provides all state attributes and low-level helpers.
Each feature mixin implements a slice of behaviour (identify, import,
review, modify, ...) and is combined into :class:`MenuScreen`.

Because mixins reference attributes defined on ``MenuScreenCore``, and
``MenuScreenCore`` dispatches to methods defined on mixins, Pyright cannot
see the full surface from either side in isolation. This Protocol makes
the contract explicit:

- every mixin inherits ``MenuScreenProto`` → sees core attrs/helpers.
- ``MenuScreenCore`` inherits ``MenuScreenProto`` → sees mixin methods.

At runtime the Protocol is a pure marker; the real implementation is
resolved through :class:`MenuScreen`'s MRO (mixins first, then core).
"""

import subprocess
from typing import Any, Protocol

from textual.app import App

from music_manager.core.config import Paths
from music_manager.core.models import PendingTrack, Track
from music_manager.options.import_tracks import ImportResult
from music_manager.options.modify_track import AlbumMatch, TrackMatch
from music_manager.services.albums import Albums
from music_manager.services.tracks import Tracks

# ── Entry point ──────────────────────────────────────────────────────────────


class MenuScreenProto(Protocol):
    """Shared contract between :class:`MenuScreenCore` and feature mixins."""

    # ── Textual base ──────────────────────────────────────────────────────
    app: App

    def query_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def focus(self, scroll_visible: bool = True) -> Any: ...

    # ── Core state ────────────────────────────────────────────────────────
    _tracks_count: int
    _albums_count: int
    _identified_count: int
    _tracks_store: Tracks | None
    _albums_store: Albums | None
    _paths: Paths | None
    _requests_path: str
    _playlists_dir: str

    # ── Navigation state ──────────────────────────────────────────────────
    _view: str
    _cursor: int
    _items: list[tuple[str, str] | None]
    _selectable: list[int]
    _return_to: str
    _cancel_requested: bool

    # ── Import state ──────────────────────────────────────────────────────
    _import_queue: list[str]
    _import_queue_idx: int
    _import_lines: list
    _import_csv: str
    _import_total: int
    _import_result: ImportResult | None

    # ── Review state ──────────────────────────────────────────────────────
    _pending: list[PendingTrack]
    _pending_idx: int
    _review_cursor: int
    _review_options: list[str]
    _review_skipped: int
    _review_deleted: int
    _review_ignored: int
    _accepted: list[tuple[PendingTrack, str, Track | dict | None]]
    _to_delete: list[PendingTrack]
    _batch_cursor: int
    _batch_import_idx: int
    _batch_import_done: int
    _search_type: str

    # ── Preview state ─────────────────────────────────────────────────────
    _preview_proc: subprocess.Popen | None

    # ── Fix-metadata state ────────────────────────────────────────────────
    _fix_albums: list
    _fix_album_idx: int
    _fix_result: dict
    _fix_checks: list[bool]
    _fix_cursor: int
    _fix_actions: list[str]
    _fix_unique_indices: list[int]
    _fix_explicit_queue: list[tuple[str, bool]]

    # ── Maintenance state ─────────────────────────────────────────────────
    _maintenance_pending: tuple[str, int]

    # ── Export state ──────────────────────────────────────────────────────
    _export_playlists: list[tuple[str, int]]
    _export_checks: list[bool]
    _export_cursor: int
    _export_actions: list[str]

    # ── Complete-albums state ─────────────────────────────────────────────
    _complete_albums: list[dict]
    _complete_checks: list[bool]
    _complete_cursor: int
    _complete_actions: list[str]

    # ── Duplicates state ──────────────────────────────────────────────────
    _dup_groups: list[list[dict]]
    _dup_best: list[int]
    _dup_idx: int
    _dup_cursor: int
    _dup_actions: list[str]
    _dup_result: dict

    # ── Modify track state ────────────────────────────────────────────────
    _modify_unmatched: list
    _modify_track_items: list[tuple[str, str, str]]
    _modify_album_items: list[tuple[str, str, int]]
    _modify_selectable: list[int]
    _modify_cursor: int
    _modify_selected_track: TrackMatch | None
    _modify_selected_album: AlbumMatch | None
    _modify_actions_items: list[tuple[str, str] | None]
    _modify_actions_selectable: list[int]
    _modify_editions: list[dict]
    _modify_covers: list[dict]
    _modify_meta_fields: list[tuple[str, str, str]]
    _modify_meta_changes: dict
    _modify_editing_field: str
    _modify_tracks_data: list
    _modify_albums_data: list

    # ── Identify state ────────────────────────────────────────────────────
    _identify_result: object
    _identify_albums_to_review: list[dict]
    _identify_singles_no_album: list[str]
    _identify_album_idx: int
    _identify_apple_ids: list[str]
    _identify_best_edition: int

    # ── Core helpers (implemented in MenuScreenCore) ──────────────────────
    def _set_header(self, content: Any) -> None: ...
    def _set_body(self, content: Any, check_scroll: bool = True) -> None: ...
    def _set_help(self, text: str, with_newline: bool = True) -> None: ...
    def _enable_scroll(self) -> None: ...
    def _disable_scroll(self) -> None: ...
    def _scroll_to_cursor(self, content: Any) -> None: ...
    def _switch_view(self, view: str) -> None: ...
    def _save_all(self) -> None: ...
    def _refresh_stats(self) -> None: ...
    def _refresh_menu(self) -> None: ...
    def _build_main(self) -> list[tuple[str, str] | None]: ...
    def _scan_csvs(self, directory: str) -> list[tuple[str, str]]: ...
    def _count_done(self, rows: list[dict]) -> int: ...
    def _is_in_library(self, row: dict) -> bool: ...

    # ── Mixin methods (dispatched from MenuScreenCore) ────────────────────
    # Identify
    def _start_identify(self) -> None: ...
    def _identify_start_review(self) -> None: ...
    def _identify_next_album(self) -> None: ...
    def _identify_preview_album(self) -> None: ...
    def _identify_album_select(self) -> None: ...
    def _identify_show_summary(self) -> None: ...
    def _identify_ignore_track(self, pending: PendingTrack) -> None: ...
    def _execute_identify_confirmations(self) -> None: ...

    # Import
    def _start_import(self, csv_path: str) -> None: ...
    def _start_import_all(self) -> None: ...
    def _finish_import(self) -> None: ...

    # Review
    def _pre_review(self) -> None: ...
    def _start_review(self, pending: list[PendingTrack]) -> None: ...
    def _render_review(self) -> None: ...
    def _review_move(self, direction: int) -> None: ...
    def _review_select(self) -> None: ...
    def _review_skip(self) -> None: ...
    def _handle_batch_decision(self) -> None: ...
    def _hide_search_input(self) -> None: ...

    # Modify
    def _start_modify(self) -> None: ...
    def _show_modify_search(self) -> None: ...
    def _hide_modify_search(self) -> None: ...
    def _show_modify_actions(self) -> None: ...
    def _modify_select(self) -> None: ...
    def _modify_select_result(self) -> None: ...
    def _modify_run_replace_url(self, youtube_url: str) -> None: ...
    def _modify_preview_cover(self) -> None: ...
    def _modify_preview_edition(self) -> None: ...
    def _refresh_modify_search(self) -> None: ...
    def _refresh_modify_actions(self) -> None: ...
    def _refresh_modify_covers(self) -> None: ...
    def _refresh_modify_editions(self) -> None: ...
    def _refresh_modify_metadata(self) -> None: ...
    def _hide_modify_input(self) -> None: ...
    def _handle_unmatched_decision(self) -> None: ...
    def _on_modify_done_with_unmatched(
        self, success: bool, error: str, unmatched: list
    ) -> None: ...

    # Fix-metadata
    def _start_fix_metadata(self) -> None: ...
    def _fix_move(self, direction: int) -> None: ...
    def _fix_select(self) -> None: ...
    def _refresh_fix_body(self) -> None: ...

    # Duplicates
    def _start_duplicates(self) -> None: ...
    def _dup_move(self, direction: int) -> None: ...
    def _dup_select(self) -> None: ...
    def _dup_skip(self) -> None: ...
    def _dup_preview(self) -> None: ...

    # Complete
    def _start_complete(self) -> None: ...
    def _complete_select(self) -> None: ...
    def _refresh_complete_body(self) -> None: ...

    # Export
    def _start_export(self) -> None: ...
    def _export_select(self) -> None: ...
    def _refresh_export_body(self) -> None: ...

    # Maintenance
    def _run_maintenance(self, key: str) -> None: ...
    def _confirm_maintenance(self) -> None: ...
    def _refresh_maintenance_confirm(self) -> None: ...
    def _show_move_data_input(self) -> None: ...

    # Preview
    def _play_preview(self, url: str) -> None: ...
    def _play_preview_fresh(self, deezer_id: int) -> None: ...
    def _preview_cover(self) -> None: ...
